import { CommitmentPeriodicity } from "../enums/commitment-periodicity.enum";
import { CommitmentType } from "../enums/commitment-type.enum";

/**
 * Represents a financial commitment.
 * A financial commitment is any future financial obligation that the user has assumed or plans to assume.
 * These commitments are essential for forecasting expenses and managing budgets effectively.
 */
export interface Commitment {
    /**
     * Unique identifier for the commitment.
     * This is generated by the application.
     */
    id: string;

    /**
     * The type of the financial commitment. Determines the specific nature of the commitment.
     * Possible values are:
     * - 'recurring' for recurring commitments
     * - 'one_time' for one-time commitments
     * - 'installment' for installment commitments
     */
    type: CommitmentType;

    /**
     * A textual description of the commitment.
     * Provides details about the nature of the commitment (e.g., "Payment for furniture purchase").
     */
    description: string;

    /**
     * The monetary amount associated with the commitment.
     * This value is always required and must be a valid number.
     */
    amount: number;


    /**
     * The due date for the commitment.
     * Applicable for commitments that have a specific due date, such as fixed, one-time, or planned commitments.
     * The date format should be ISO 8601 (e.g., "2024-10-15").
     */
    due_date?: string;

    /**
     * The start date of the commitment.
     * Applicable for recurring and installment commitments.
     * The date format should be ISO 8601 (e.g., "2024-09-01").
     */
    start_date?: string;

    /**
     * The end date of the commitment.
     * Optional for recurring and installment commitments.
     * The date format should be ISO 8601 (e.g., "2025-09-01").
     */
    end_date?: string;

    /**
     * The periodicity of the commitment.
     * Defines how often a recurring commitment occurs.
     * 
     * Possible values:
     * - `weekly`: The commitment occurs once a week.
     * - `biweekly`: The commitment occurs every 14 days.
     * - `monthly`: The commitment occurs once a month.
     * - `quarterly`: The commitment occurs every three months.
     * - `yearly`: The commitment occurs once a year.
     */
    periodicity?: CommitmentPeriodicity;

    /**
     * The total number of installments for the commitment.
     * Applicable for installment commitments, representing how many payments are divided over time.
     */
    installments?: number;

    /**
     * The current installment number for the commitment.
     * Applicable for installment commitments to track which payment is currently being processed.
     */
    current_installment?: number;

    /**
     * The category of the commitment.
     * Used to classify the commitment into broad categories (e.g., "Utilities", "Entertainment").
     */
    category: string;

    /**
     * The subcategory of the commitment.
     * Optional and used for more specific classification within the main category (e.g., "Streaming Services").
     */
    subcategory?: string;
}
